// Generated by Vue on Rails https://github.com/vueonrails/vueonrails
// A simple state management as described in https://vuejs.org/v2/guide/state-management.html

var store = {
  debug: true,
  state: {
    message: "Hello from Simple Store!"
  },
  setMessageAction(newValue) {
    if (this.debug) console.log("setMessageAction triggered with", newValue);
    this.state.message = newValue;
  },
  clearMessageAction() {
    if (this.debug) console.log("clearMessageAction triggered");
    this.state.message = "";
  }
};

export default store;
