// Generated by Vue on Rails https://github.com/vueonrails/vueonrails

// Generate these JSON locales by running command: rails vue:translate
// import en from "./en.json";
// import cn from "./cn.json";

// Import the created JSON locales after running vue:translate command
const messages = {
  // ...en,
  // ...cn
};

import Vue from "vue";
import VueI18n from "vue-i18n";
Vue.use(VueI18n);

const i18n = new VueI18n({
  locale: "en",
  messages
});

export default i18n;
